### ISSUE TITLE
Mock gets injected instead

### ISSUE THREAD

**Issue by bmarwell** [needle4j/needle4j#23]
Hello,

I got this in my code:

```java
  @ClassRule
  public static DatabaseTestRule databaseRule = new DatabaseTestRuleBuilder()
      .withDBOperation(LiquibaseInitDbOperation.class)
      .withPersistenceUnit(JpaEntityDaoTest.class.getSimpleName())
      .build();

  @Rule
  public NeedleRule needleRule = new NeedleRule(databaseRule);

  @ObjectUnderTest(implementation = EntityRepositoryImpl.class)
  private EntityRepository entityRepository;

  @InjectIntoMany
  @ObjectUnderTest(implementation = JpaEntityDao.class)
  private EntityDao entityDao;
```

Now,  entityDao is just fine and got its entityManager.

But: entityRepository's dao is a Mock! from logging perspective, if I print the toString() method, it looks like this:
```java
EntityRepositoryImpl{dao=Mock for EntityDao, hashCode: -2036337708}
```

I also verified: I got two Constructors on my RepositoryImpl: One no-arg for CDI, and one annotated with `@Inject` and a single argument: `EntityDao dao`.

I re-read the  documentation many times, and I also tried to use `@InjectInto(…)` instead. No luck.

Either the documentation is missing something, I am blind, or I discovered a bug. 
Help appreciated.

This is my `needle.properties` file:
```properties
mock.provider=org.needle4j.mock.MockitoProvider
```

**Comment by bmhm** [comment]
I just checked the source file: https://github.com/needle4j/needle4j/blob/master/src/main/java/org/needle4j/NeedleTestcase.java

It seems that constructor injection will not work together with `@InjectInto` and `@InjectIntoMany`, because the method `initInstance(instance)` is the only method which will inject existing instances or create new ones. This is called in line 101.

That being said, constructor injection will always create mocks as I can read from the source code.

**Comment by mdahm** [comment]
This issue has been fixed in needle4k:

https://github.com/needle4k/needle4k
