### ISSUE TITLE
HSQLDeleteOperation is not working with Hibernate 4.3

### ISSUE THREAD

**Issue by needle4j-org** [needle4j/needle4j#8]
originally by @OliverDamm

The HSQLDeleteOperation tries to open a JDBC connection using the properties from the EntityManagerFactory.getProperties() method. Hibernate 4.3 is masking out sensitive properties like the password property. So, the HSQLDeleteOperation tries to create a connection with a wrong password like '****'.

Setting the password directly in the needle.properties using 'jdbc.password' don't help.

Needle Version 2.2

Oliver

**Comment by jellisgwn** [comment]
are you interested in a patch for this issue?

to maintain compatibility with older Hibernate versions i added a 'needle4j.jdbc.password' property that overrides 'javax.persistence.jdbc.password' when present. the change is limited, only a couple of lines in org.needle4j.db.DatabaseTestcaseConfiguration.java.

let me know and i'll submit a change....

**Comment by jangalinski** [comment]
Thanks, I will have a look at it.

**Comment by jellisgwn** [comment]
Had a little more time to look at the code again, and can suggest an alternative approach.

Instead of adding new properties to persistence.xml, it might be more intuitive to use the existing JDBC properties that are defined in the needle4j.properities file. 

The logic would be essentially the same:

- the javax.persistence.jdbc.password is defined in persistence.xml then attempt to use that value. If it is not defined, then try to connect with the value from NeedleConfiguration.getJdbcPassword(). To keep things symmetrical looking the same can be done with the JDBC username.

This feels less of a hack than my original change. Let me know if you'd like such a change and i'll create another pull request!

**Comment by jangalinski** [comment]
I have to admin, I am not very famiiar with this issue. Your last PR broke the build somehow ... could you perhaps start  with a breaking test case that is then fixed by your addition? Would make it easier to follow what you are doing ...
